version: 2
general:
  branches:
    only:
     - master
jobs:
   build:
     working_directory: ~/release-test
     docker:
       - image: circleci/node:7
     steps:
       - checkout
       - run: npm install
       - run: ~/release-test/node_modules/.bin/semantic-release-github
